<!DOCTYPE html>
<!--[if IE 9]><html class="ie ie9"> <![endif]-->
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="keywords" content="Home cooked, Delivery, Fresh, Pure, Take Away, Meals, Delicious, Healthy, Nutritious, Ingredients, Comfortable, Timely">
    <meta name="description" content="">
    <meta name="author" content="varunsk23@gmail.com">

    <title>HungerMeals</title>

    <!-- Favicons-->
    <link rel="shortcut icon" href="../images/favicon.ico" type="image/x-icon">
    <link rel="apple-touch-icon" type="image/x-icon" href="../images/apple-touch-icon-57x57-precomposed.png">
    <link rel="apple-touch-icon" type="image/x-icon" sizes="72x72" href="../images/apple-touch-icon-72x72-precomposed.png">
    <link rel="apple-touch-icon" type="image/x-icon" sizes="114x114" href="../images/apple-touch-icon-114x114-precomposed.png">
    <link rel="apple-touch-icon" type="image/x-icon" sizes="144x144" href="../images/apple-touch-icon-144x144-precomposed.png">
    
    <!-- BASE CSS -->
    <link href="../scripts/css/base.css" rel="stylesheet">
    
    <!-- Radio and check inputs -->
    <link href="../scripts/css/skins/square/grey.css" rel="stylesheet">
    


    <!--[if lt IE 9]>
      <script src="js/html5shiv.min.js"></script>
      <script src="js/respond.min.js"></script>
    <![endif]-->
</head>

<body>

<!--[if lte IE 8]>
    <p class="chromeframe">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a>.</p>
<![endif]-->

	<div id="preloader">
        <div class="sk-spinner sk-spinner-wave" id="status">
            <div class="sk-rect1"></div>
            <div class="sk-rect2"></div>
            <div class="sk-rect3"></div>
            <div class="sk-rect4"></div>
            <div class="sk-rect5"></div>
        </div>
    </div><!-- End Preload -->

    <!-- Header ================================================== -->
    <header>
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-4 col-sm-4 col-xs-4">
            </div>
            <div class="col-md-3 col-sm-3 col-xs-3 text-center">
                <a href="index.jsp" id="logo">
                <img src="../images/logo.png" width="190" height="23" alt="" data-retina="true" class="hidden-xs">
                <img src="../images/logo_mobile.png" width="30" height="23" alt="" data-retina="true" class="hidden-lg hidden-md hidden-sm">
                </a>
            </div>
            <nav class="col-md-5 col-sm-5 col-xs-5">
            <a class="cmn-toggle-switch cmn-toggle-switch__htx open_close" href="javascript:void(0);"><span>Menu mobile</span></a>
            <div class="main-menu">
                <div id="header_menu">
                    <img src="../images/logo.png" width="190" height="23" alt="" data-retina="true">
                </div>
                <a href="#" class="open_close" id="close_in"><i class="icon_close"></i></a>
                 <ul id="head_menu">
                    <li><a href="about.jsp">About</a></li>
                    <li><a href="mymeal.jsp">Make My Meal</a></li>
                    <li id="login_link"><a href="#0" data-toggle="modal" data-target="#login_2">Login</a></li>
                </ul>
            </div><!-- End main-menu -->
            </nav>
        </div><!-- End row -->
    </div><!-- End container -->
    </header>
    <!-- End Header =============================================== -->

<!-- Content ================================================== -->
<div class="container margin_60_35">
	<div class="row margin_60_35">
			<h3>Terms & Conditions</h3>
		<div class="col-lg-12 white_bg termsnpolicy">
			<p>
			In terms of Information Technology Act, 2000, this document is an electronic record. Being generated by a computer system it does not require any physical or digital signatures. This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage ofhttp://www.hungermeals.com. (a) The domain name http://www.hungermeals.com.(hereinafter referred to as “the Website”) is owned by RSV Food Tech, a Partnership Firm incorporated under The Indian Partnership Act, 1932 having its registered office at HSR Layout, sector 2. (b) For the purpose of these Terms of Use, wherever the context so requires "You" or "User" shall mean any natural or legal person who has agreed to become a buyer on the Website and ordering the Goods and Services available on the Website by providing Registration Data while registering on the Website. The site also providing its services without registration does not absolve you of this contractual relationship. The term "We", "Us", "Our" or “HungerMeals” shall mean the Firm. The headings of each section in this Agreement are only for the purpose of organizing the various provisions under this Agreement in an orderly manner. These headings shall not be used by either party to interpret the provisions contained with them in any manner. Further, the headings have no legal or contractual value. (c) The use of this Website by You is solely governed by this policy and any policy so mentioned by terms of reference. Moving past home page or using any of the services shall be taken to mean that you have read and agreed to be bound by all of the policies. You will be subject to the rules, guidelines, policies, terms, and conditions applicable to any service that is provided by this site, and they shall be deemed to be incorporated into this Terms of Use and shall be considered as part and parcel of this Terms of Use. (d) We hold the sole right to modify the Terms of Service without prior permission from you or informing you. The relationship creates on you a duty to periodically check the terms and stay updated on its requirements. If you continue to use the website following such a change, this is deemed as consent by you to the so amended policies. As long as you comply with these Terms of Use, We grant you a personal, non-exclusive, non-transferable, limited privilege to enter and use the Website.
			</p>
			<p>	
			HungerMeals is an online platform that delivers home-cooked north Indian and Andhra meals. HungerMeals will list their meals/dishes/signature preparations on the platform, and any User can scroll through different eating options available and place an order. We take the orders, collect payments and deliver the food at the doorstep of the User.
			</p>

			<label>2. Agreement to Terms</label> 
			<p>				
			By using our Services, you agree to be bound by these Terms. If you don’t agree to these Terms, do not use the Services. If you are accessing and using the Services on behalf of a company (such as your employer) or other legal entity, you represent and warrant that you have the authority to bind that company or other legal entity to these Terms. In that case, “you” and “your” will refer to that company or other legal entity.
			</p>

			<label>3. Changes to Terms or Services</label> 
			<p>							
			We may modify these Terms at any time, in our sole discretion. If we do so, we’ll let you know either by posting the modified Terms on the Site, in our App, or through other communications. It’s important that you review the Terms whenever we modify them because if you continue to use the Services after we have posted modified Terms on the Site or in our App or have communicated them to you, you are indicating to us that you agree to be bound by the modified Terms. If you don’t agree to be bound by the modified Terms, then you can’t use the Services anymore. Because our Services are evolving over time we may change or discontinue all or any part of the Services, at any time and without notice, at our sole discretion.
			</p>

			<label>4. Registration and Your Information</label> 
			<p>							
			If you want to use certain features of the Services you’ll have to create an account (“Account”). You can do this on our Site, in our App, or through your account with certain third-party social networking services, such as Facebook or Twitter. It’s important that you provide us with accurate, complete, and up-to-date information for your Account, so you agree to update such information, as needed, to keep it accurate, complete, and up-to-date. If you don’t, we might have to suspend or terminate your Account. You agree that you won’t disclose your Account password to anyone and that you’ll notify us immediately of any unauthorized use of your Account. You’re responsible for all activities that occur under your Account, whether or not you know about them, so please keep your password secret and secure.
			We want to keep all our users safe and happy, so we reserve the right, in our sole discretion, to disable, suspend, cancel, or delete any Account for any reason, or to refuse any user access to any of our Services, if we think doing so will help keep things safe and enjoyable for everybody.
			</p>

			<label>5. Buying Meals</label> 
			<p>							
			When you buy a Meal on a one off basis or as part of a subscription through any of our Services (such purchase, a “Transaction”), we may ask you to supply additional information relevant to your Transaction, including, without limitation, , the expiration date of your credit card, and your addresses for billing and delivery (such information, “Payment Information”). You represent and warrant that you have the legal right to use all payment method(s) represented by any such Payment Information, whether you provide it in the course of a Transaction or in connection with your Account. When you initiate a Transaction, you authorize us to provide your Payment Information to third parties so we can complete your Transaction and to charge your payment method for the type of Transaction you have selected; you may need to provide additional information to verify your identity before completing your Transaction (such information is included within the definition of Payment Information).
			All sales are final. But if something unexpected happens in the course of fulfilling your order, we reserve the right to cancel your order for any reason; if we cancel your individual order or an order part of a subscription, we’ll refund any payment you may already have remitted to us.
			</p>

			<label>6. HungerMeals Plans</label> 			
			<p>							
			From time to time HungerMeals may make different plans available via the Services, including our Membership Program and Subscription Program. All HungerMeals plans may not be available in all delivery areas. If you are located in an included area, you can join a HungerMeals ‘make my meal’ plan by signing up and paying a monthly or annual membership fee (“Program Fee”), as applicable.
			</p>

			<label>7. Cancellation and Refunding Policy</label>
			<p>							
			Once you place an order, within 15 minutes your parcel will be dispatched, hence any cancellation required to be done has to be made within 15 minutes. Meal subscription can be cancelled two days prior to unsubscribing it. The refund will be returned in three working days from the date of cancellation.
			</p>

			<label>8. Your Rights in Our Content</label>
			<p>							
			Subject to your compliance with these Terms, we grant you a limited, non-exclusive, non-transferable, non-sublicense able license to access and view the Content solely in connection with your permitted use of our Services and solely for your personal and non-commercial purposes.
			General Prohibitions and Our Enforcement Rights
			You agree not to do any of the following:
			Use, display, mirror, or frame (i) our Site or App or any individual element within our Site, Services, or App; (ii) HungerMeals name or any HungerMeals trademark, logo, or other proprietary information; (iii) the layout and design of any page or form contained on a page without HungerMeals express written consent;
			Access, tamper with, or use non-public areas of the Site or App, HungerMeals computer systems, or the technical delivery systems of HungerMeals providers;
			Attempt to probe, scan, or test the vulnerability of any HungerMeals system or network or breach any security or authentication measures;
			Avoid, bypass, remove, deactivate, impair, descramble, or otherwise circumvent any technological measure implemented by HungerMeals or any of HungerMeals providers or any other third party (including another user) to protect the Site, App, Services, or any of their Content;
			Attempt to access or search the Site, App, Services, or any of their Content or download any Content from them through the use of any engine, software, tool, agent, device, or mechanism (including spiders, robots, crawlers, data-mining tools, and the like) other than the software or search agents provided by us or other generally available third-party web browsers;
			Send any unsolicited or unauthorized advertising, promotional materials, email, junk mail, spam, chain letters, or other form of solicitation;
			Use any meta tags or other hidden text or metadata utilizing a HungerMeals trademark, logo URL, or product name without our express written consent;
			Use the Site, App, Services, or any of their Content for any commercial purpose or the benefit of any third party or in any manner not permitted by these Terms;
			Forge any TCP/IP packet header or any part of the header information in any email or newsgroup posting or in any way use the Site, App, Services, or any of their Content to send altered, deceptive, or false source-identifying information;
			Attempt to decipher, decompile, disassemble, or reverse engineer any of the software used to provide the Site, App, Services, or any of their Content;
			Interfere with, or attempt to interfere with, the access of any user, host, or network, including, without limitation, sending a virus, overloading, flooding, spamming, or mail-bombing the Site, App, or Services;
			Collect or store any personally identifiable information from the Site, App, or Services from any other user without the user’s express permission;
			Impersonate or misrepresent your affiliation with any person or entity;
			Violate any applicable law or regulation; or
			Encourage or enable any other individual to do any of the foregoing.
			Although we’re not obligated to monitor access to or use of the Services or Content or to review or edit any Content, we have the right to do so for the purpose of operating the Services, to ensure compliance with these Terms, and to comply with applicable law or other legal requirements. We reserve the right, but are not obligated, to remove or disable access to any Content, at any time and without notice, including, but not limited to, if we, at our sole discretion, consider any Content to be objectionable or in violation of these Terms. We have the right to investigate violations of these Terms or conduct that affects the Services. We may also consult and cooperate with law enforcement authorities to prosecute users who violate the law.
			We’re not responsible for the availability of outside websites or resources linked from our Site or our App. We don’t endorse and aren’t responsible or liable for any content, advertisements, products, or other materials on or available from such websites or resources. You understand and agree that we won’t be responsible or liable, directly or indirectly, for any damage or loss caused, or alleged to be caused, by or in connection with the use of or reliance on any such content, goods, or services available on or through any such third-party websites or resources.
			</p>

			<label>9. App Policies</label>
			<p>							
			Subject to your compliance with these Terms, we grant you a limited non-exclusive, non-transferable, non-sublicense able license to download and install a copy of our App on a mobile device or computer that you own or control and to run such copy of the App solely for your own personal non-commercial purposes. You may not copy our App, except to make a reasonable number of copies for backup or archival purposes. Except as expressly permitted in these Terms, you may not: (i) copy, modify, or create derivative works based on the App; (ii) distribute, transfer, sublicense, lease, lend, or rent the App to any third party; (iii) reverse engineer, decompile, or disassemble the App; or (iv) make the functionality of the App available to multiple users through any means. We reserve all rights in and to the App not expressly granted to you under these Terms.
			If you accessed or downloaded our App from any app store or distribution platform (such as the Apple Store, Google Play, and the Amazon App store) (each, an “App Provider”), then you acknowledge and agree that:
			These Terms are concluded between you and us, and not with App Provider, and, as between HungerMeals and the App Provider, HungerMeals is solely responsible for the App.
			App Provider has no obligation to furnish any maintenance and support services with respect to the App.
			In the event of any failure of the App to conform to any applicable warranty, you may notify App Provider and App Provider will refund the purchase price for the App to you (if applicable) and, to the maximum extent permitted by applicable law, App Provider will have no other warranty obligation whatsoever with respect to the App. Any other claims, losses, liabilities, damages, costs, or expenses attributable to any failure of an App to conform to any warranty will be the sole responsibility of HungerMeals.
			App Provider is not responsible for addressing any claims you have or any claims of any third party relating to the App or your possession and use of the App, including, but not limited to: (i) product liability claims; (ii) any claim that the App fails to conform to any applicable legal or regulatory requirement; and (iii) claims arising under consumer protection or similar legislation.
			In the event of any third-party claim that the App or your possession and use of the App infringes that third party’s intellectual-property rights, HungerMeals will be solely responsible for the investigation, defense, settlement, and discharge of any such intellectual-property infringement claim to the extent required by these Terms.
			App Provider and its subsidiaries are third-party beneficiaries of these Terms as related to your license of the App, and, upon your acceptance of the terms and conditions of these Terms, App Provider will have the right (and will be deemed to have accepted the right) to enforce these Terms as related to your license of the App against you as a third-party beneficiary.
			You must comply with all applicable third-party terms of service when using the App.
			You will comply with all U.S. and foreign export laws and regulations to ensure that neither the App nor any technical data related thereto nor any direct product thereof is exported or re-exported directly or indirectly in violation of, or used for any purposes prohibited by, such laws and regulations, and you are not located in a country that is subject to a U.S. Government embargo or that has been designated by the U.S. Government as a “terrorist supporting” country. You are not listed on any U.S. Government list of prohibited or restricted parties.
			</p>

			<label>10. Termination</label>
			<p>							
			We may terminate your access to and use of the Services, at our sole discretion, at any time and without notice to you. You may cancel your Account at any time by sending an email to us. Upon any termination, discontinuation, or cancellation of Services or your Account, the following Terms will survive: content ownership, warranty disclaimers, limitations of liability, and dispute resolution.
			Indemnity
			You will indemnify and hold harmless HungerMeals  and our officers, directors, employee, and agents, from and against any claims, disputes, demands, liabilities, damages, losses, and costs and expenses, including, without limitation, reasonable legal and accounting fees arising out of or in any way connected with (i) your access to or use of the Services or (ii) your violation of these Terms.
			If you have any questions about these Terms or the Services, please contact us at 9986122222.
			</p>

		</div>
	</div><!-- End row -->
	<div class="row margin_60_35">
		<h3>Privacy & Terms</h3>
		<div class="col-lg-12 white_bg termsnpolicy">
			<p>							
			Welcome to HungerMeals! Protecting your privacy is really important to us. Hence, we’re providing this Privacy Policy to explain our practices regarding the collection, use, and disclosure of information that we receive when you use our Services. Any information that we collect is subject to the privacy policy in effect at the time that Information is collected. We may, however, modify and revise this Privacy Policy from time to time. If we make any material changes to this Privacy Policy, we’ll notify you of those changes by posting them on the Services or by sending you an email or other notification, and we’ll indicate when those changes will become effective. 

			The information We Collect
			Our primary goals in collecting information are to provide and improve our Services, to administer your use of the Services (including your Account, if you are an Account holder), and to enable you to enjoy and easily navigate our Services. If you decide at any time that you no longer wish to receive such communications from us, please follow the unsubscribe instructions provided in the applicable communications.
			.
			If you create an Account, we’ll collect certain information that can be used to identify you, such as your name, email address, postal address, phone number, and credit-card number or other billing information. Like many website and mobile-application operators, we use automated data collection tools such as Cookies to collect certain information.
			</p>

			<label>2. Cookies</label>
			<p>										
			They are small text files that are placed on your hard drive by a Web server when you access our Services. We may use both session Cookies and persistent Cookies to identify that you’ve logged in to the Services and to tell us how and when you interact with our Services. We may also use Cookies to monitor aggregate usage and web traffic routing on our Services and to customize and improve our Services. Unlike persistent Cookies, session Cookies are deleted when you log off from the Services and close your browser. Although most browsers automatically accept Cookies, you can change your browser options to stop automatically accepting Cookies or to prompt you before accepting Cookies. Please note, however, that if you don’t accept Cookies, you may not be able to access all portions or features of the Services. Some third-party services providers that we engage (including third-party advertisers) may also place their own Cookies on your hard drive. Note that this Privacy Policy covers only our use of Cookies and does not include use of Cookies by such third parties.
			Our Use of Your Information

			Your contact information is also used to contact you whenever necessary. We use your IP address to help diagnose problems with our server, and to administer our Website. Your IP address is also used to help identify you and to gather broad demographic information. Finally, we may use your IP address to help protect our partners and ourselves from fraud. We will continue to enhance our security procedures as new technology becomes available. We will transfer information about you if we are acquired by or merged with another company. In this event, we will notify you by email or by putting a prominent notice on the site before information about you is transferred and becomes subject to a different privacy policy. We may release your personal information to a third-party in order comply with a Court Order or other similar legal procedure, or when we believe in good faith that such disclosure is necessary to comply with the law; prevent imminent physical harm or financial loss; or investigate or take action regarding illegal activities, suspected fraud, or violations of Our Terms of Service. We may disclose personally identifiable information to parties in compliance with our Copyright Policy as mentioned in the Terms of Service as we in our sole discretion believe necessary or appropriate in connection with an investigation of fraud, intellectual property infringement, piracy, or other unlawful activity. In such events, We may disclose name, address, country, phone number, email address and company name.
			</p>

			<label>3. Security of Your Information</label>
			<p>													
			We take reasonable measures to protect the information that we collect from or about you (including your PII) from unauthorized access, use, or disclosure. Please be aware, however, that no method of transmitting information over the Internet or storing information is completely secure. Accordingly, we can’t guarantee the absolute security of any information.
			Identity theft and “phishing” are of great concern to us. Safeguarding your information to help protect you is a top priority for us. If you suspect someone is trying to impersonate us or misleading you or other members of our community about the suspect person’s relationship to us or to our Services, please contact us.
			</p>

			<label>4. Our disclosure of your information</label>
			<p>																
			Due to the existing regulatory environment, we cannot ensure that all of your private communications and other personally identifiable information will never be disclosed in ways not otherwise described in this Privacy Policy. By way of example (without limiting and foregoing), we may be forced to disclose information to the government, law enforcement agencies or third parties. Under certain circumstances, third parties may unlawfully intercept or access transmissions or private communications, or members may abuse or misuse your information that they collect from our Website. Therefore, although we use industry standard practices to protect your privacy, we do not promise, and you should not expect, that your personally identifiable information or private communications would always remain private. As a matter of policy, we do not sell or rent any personally identifiable information about you to any third party. However, the following describes some of the ways that your personally identifiable information may be disclosed. 8.1 External Service Providers: There may be a number of services offered by external service providers that help you use our Websites. If you choose to use these optional services, and in the course of doing so, disclose information to the external service providers, and/or grant them permission to collect information about you, then their use of your information is governed by their private policy. 8.2 Other Corporate Entities: We share much of our data, including personally identifiable information about you, with our parent and/or subsidiaries that are committed to serving your online needs and related services, throughout the world. Such data will be shared for the sole purpose of enhancing your browsing experience. To the extent that these entities have access to your information, they will treat it at least as protectively as they treat information they obtain from their other members. It is possible that We and/or its subsidiaries, or any combination of such, could merge with or be acquired by another business entity. Should such a combination occur, you should expect that we would share some or all of your information in order to continue to provide the service. You will receive notice of such event (to the extent that it occurs). 8.3 Law and Order: We cooperate with law enforcement inquiries, as well as other third parties to enforce laws, such as: intellectual property rights, fraud and other rights. We can (and you authorize us to) disclose any information about you to law enforcement and other government officials as we, in our sole discretion, believe necessary or appropriate, in connection with an investigation of fraud, intellectual property infringements, or other activity that is illegal or may expose us or you to legal liability.
			</p>

			<label>5. Links to Other Sites</label>
			<p>																
			Our Services may contain links to other websites and services. Any information that you provide on or to a third-party website or service is provided directly to the owner of the website or service and is subject to that party’s privacy policy. Our Privacy Policy does not apply to such websites or services, and we’re not responsible for the content, privacy or security practices and policies of those websites or services. To protect your information we recommend that you carefully review the privacy policies of other websites and services that you access.
			</p>

		</div>
	</div><!-- End row -->
</div><!-- End container -->
<!-- End Content =============================================== -->

<!-- Footer ================================================== -->
    <footer>
        <div class="container">
        <div class="row">
            <div class="col-md-6 col-sm-6">
                <h3>About</h3>
                <ul>
                    <li><a href="about.jsp">About us</a></li>
                    <li><a href="faq.jsp">Faq</a></li>
                    <li><a href="termsnpolicy.jsp">Terms and Policy</a></li>
                    <li><a href="contact.jsp">Contact us</a></li>
                </ul>
            </div>
            <div class="col-md-6 col-sm-6" id="newsletter">
                 
            </div>
        </div><!-- End row -->
        <div class="row">
            <div id="social_footer">
                <ul>
                    <li><a href="https://www.facebook.com/hungermeals/"><i class="icon-facebook"></i></a></li>
                    <li><a href="https://twitter.com/HungerMeals2016"><i class="icon-twitter"></i></a></li>
                    <li><a href="https://www.instagram.com/hungermeals/"><i class="icon-instagram"></i></a></li>
                </ul>
                <p>© HungerMeals 2016</p>
            </div>                
        </div><!-- End row -->
        </div><!-- End container -->
    </footer>
<!-- End Footer =============================================== -->

<div class="layer"></div><!-- Mobile menu overlay mask -->
    
<!-- Login modal -->   
<div class="modal fade" id="login_2" tabindex="-1" role="dialog" aria-labelledby="myLogin" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content modal-popup">
                <a href="#" class="close-link"><i class="icon_close_alt2"></i></a>
                <form class="popup-form" method="POST">
                    <div class="login_icon">
						<img src="pics/logo.png" width="190" height="23" alt="" data-retina="true">
                    </div>
                     <input type="text" class="form-control" placeholder="Mobile" name="username" onkeypress='return event.charCode >= 48 && event.charCode <= 57' maxlength="10">
                    <!-- <input type="text" class="form-control" placeholder="Mobile" name="username"> -->
                    <div class="text-right" title="Forgot password? You can login with OTP as well.">
                        <label>Login with <a href="#" onclick="getotp();" id="otpRequest">Instant OTP?</a></label>
                    </div>
                    <input type="password" class="form-control" placeholder="Password" name="password">
                   	<div id="error_statusTxt" class="weakpass" style="display:none;"></div>
                    <button type="submit" class="btn btn-submit" id="myLogin">
                    	<i class="icon-spin6 animate-spin" id="myLoginSpin" style="display:none;"></i>
                    	Submit
                    </button>
                </form>
                <label>New to HungerMeals? <a href="#0" data-toggle="modal" data-target="#register">Sign Up</a></label>
            </div>
        </div>
    </div><!-- End modal -->   
    
<!-- Register modal -->   
<div class="modal fade" id="register" tabindex="-1" role="dialog" aria-labelledby="myRegister" aria-hidden="true">
		<div class="modal-dialog">
			<div class="modal-content modal-popup">
				<a href="#" class="close-link"><i class="icon_close_alt2"></i></a>
				<form class="popup-form">
                	<div class="login_icon">
						<img src="pics/logo.png" width="190" height="23" alt="" data-retina="true">
                    </div>
					<input type="text" class="form-control" placeholder="Name" name="uName">
					<input type="text" class="form-control" placeholder="Mobile" name="mobile" onkeypress='return event.charCode >= 48 && event.charCode <= 57' maxlength="10">
                    <input type="email" class="form-control" placeholder="Email" name="email">
                    <input type="password" class="form-control" placeholder="Password"  id="password1" name="password1">
                    <input type="password" class="form-control" placeholder="Confirm password"  id="password2" name="password2">
                    <div id="pass-info" class="clearfix"></div>
					<div class="checkbox-holder text-left">
						<div class="checkbox">
							<input type="checkbox" value="accept_2" id="check_2" name="check_2" />
							<label for="check_2"><span>I Agree to the <strong><a href="files/terms_conditions.pdf" target="_Blank">Terms &amp; Conditions</a></strong></span></label>
						</div>
					</div>
					<button type="button" class="btn btn-submit" id="myRegister">
						<i class="icon-spin6 animate-spin" id="myRegisterSpin" style="display:none;"></i>
						Register
					</button>
				</form>
			</div>
		</div>
	</div><!-- End Register modal -->

<div class="modal fade" id="forgotP" tabindex="-1" role="dialog" aria-labelledby="myforgotPassword" aria-hidden="true">
</div><!-- End forgotPassword modal -->

<div class="modal fade" id="hm_alert" tabindex="-1" role="dialog" aria-labelledby="myhm_alert" aria-hidden="true"></div>
<!-- End hm_alert modal -->
        
<!-- COMMON SCRIPTS -->
<script src="js/jquery-1.11.2.min.js"></script>
<script src="js/common_scripts_min.js"></script>
<script src="js/functions.js"></script>
<script src="assets/validate.js"></script>


<!-- SPECIFIC SCRIPTS -->
<script  src="js/cat_nav_mobile.js"></script>
<script>$('#cat_nav').mobileMenu();</script>
<script src="js/jquery.pin.min.js"></script>
<script>/*$("#cart_box").pin({padding: {top: 80, bottom: 25},minWidth: 1100, containerSelector: "#container_pin"})*/</script>
<script>
 $(function() {
	 'use strict';
	  $('a[href*=#]:not([href=#])').click(function() {
	    if (location.pathname.replace(/^\//,'') == this.pathname.replace(/^\//,'') && location.hostname == this.hostname) {
	      var target = $(this.hash);
	      target = target.length ? target : $('[name=' + this.hash.slice(1) +']');
	      if (target.length) {
	        $('html,body').animate({
	          scrollTop: target.offset().top - 70
	        }, 1000);
	        return false;
	      }
	    }
	  });
	});

 </script>

<!-- HUNGER SCRIPTS -->
<script src="script/js-cookie.js"></script>
<script src="script/common.js"></script>
<script src="script/credentials.js"></script>
<script>
	$(document).ready(function(){
	    setLoggedInfo();
	});
</script>

</body>
</html>